# Here i configure the namespace for the cluster
apiVersion: v1
kind: Namespace
metadata:
  name: kii-project
---
# Here i add secrets for the sensitive data used in the cluster
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kii-project
type: Opaque
stringData:
  postgres-username: emt
  postgres-password: emt
---
# Here i add configuration map for the less sensitive data used in the cluster
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: kii-project
data:
  postgres-db: emt_lab_ps

  # for local i will use standard storage class on k3d (local-path)
  # but for migrating to Azure or AWS then we change the name here
  storage-class-name: local-path

---
# Schema and view scripts mounted into Postgres on first startup
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-scripts
  namespace: kii-project
data:
  init.sql: |
    create table if not exists agency_user
    (
        is_account_non_expired     boolean      not null,
        is_account_non_locked      boolean      not null,
        is_credentials_non_expired boolean      not null,
        is_enabled                 boolean      not null,
        name                       varchar(255),
        password                   varchar(255),
        role                       varchar(255)
            constraint agency_user_role_check
                check ((role)::text = ANY (ARRAY [('ROLE_USER'::character varying)::text, ('ROLE_HOST'::character varying)::text])),
        surname                    varchar(255),
        username                   varchar(255) not null
            primary key
    );

    alter table agency_user
        owner to emt;

    create index if not exists name_and_surname_index_on_user
        on agency_user (name, surname);

    create table if not exists country
    (
        id        bigint generated by default as identity
            primary key,
        continent varchar(255),
        name      varchar(255)
    );

    alter table country
        owner to emt;

    create index if not exists continent_index_on_country
        on country (continent);

    create table if not exists host
    (
        country_id bigint
            constraint fk1mfnghhnwulxi5qe0ohfi3on2
                references country
                on delete set null,
        id         bigint generated by default as identity
            primary key,
        name       varchar(255),
        surname    varchar(255)
    );

    alter table host
        owner to emt;

    create index if not exists name_index_on_host
        on host (name);

    create index if not exists name_and_id_index_on_host
        on host (id, name);

    create index if not exists country_index_on_host
        on host (country_id);

    create table if not exists smestuvanje
    (
        num_rooms integer,
        occupied  boolean,
        host_id   bigint
            constraint fkjjh3ronoafgs4djtqumvb9ux2
                references host
                on delete set null,
        id        bigint generated by default as identity
            primary key,
        category  varchar(255)
            constraint smestuvanje_category_check
                check ((category)::text = ANY
                       (ARRAY [('ROOM'::character varying)::text, ('HOUSE'::character varying)::text, ('FLAT'::character varying)::text, ('APARTMENT'::character varying)::text, ('HOTEL'::character varying)::text, ('MOTEL'::character varying)::text])),
        korisnik  varchar(255),
        name      varchar(255)
    );

    alter table smestuvanje
        owner to emt;

    create index if not exists host_index_on_smestuvanje
        on smestuvanje (host_id);

    create index if not exists korisnik_index_on_smestuvanje
        on smestuvanje (korisnik);

    create table if not exists reservation
    (
        guest_num      integer,
        end_date       timestamp(6),
        id             bigint generated by default as identity
            primary key,
        smestuvanje_id bigint
            constraint fk6t8q78oxkt0scjil3u32kppo6
                references smestuvanje,
        start_date     timestamp(6)
    );

    alter table reservation
        owner to emt;

    create index if not exists guest_num_and_start_date_index_on_reservation
        on reservation (guest_num, start_date);

    create table if not exists agency_user_reserved_reservations
    (
        reserved_reservations_id bigint       not null
            unique
            constraint fkej9hofleuetgkd4ikqs2489sp
                references reservation,
        agency_user_username     varchar(255) not null
            constraint fk4pm39iq8ba5jlhso5paiayk1r
                references agency_user
    );

    alter table agency_user_reserved_reservations
        owner to emt;

    create table if not exists agency_user_temporary_reservations
    (
        temporary_reservations_id bigint       not null
            constraint agency_user_temporary_reservation_temporary_reservations_id_key
                unique
            constraint fkpyksg80wxatm9g9dout1bimb9
                references reservation,
        agency_user_username      varchar(255) not null
            constraint fk8tl0le989pn2gpji1qhqjjg4d
                references agency_user
    );

    alter table agency_user_temporary_reservations
        owner to emt;


    create index if not exists name_index_on_host on host(name);
    create index if not exists name_and_id_index_on_host on host(id,name);
    create index if not exists country_index_on_host on host(country_id);
    create index if not exists continent_index_on_country on country(continent);
    create index if not exists name_and_surname_index_on_user on agency_user(name,surname);
    create index if not exists guest_num_and_start_date_index_on_reservation on reservation(guest_num,start_date);
    create index if not exists host_index_on_smestuvanje on smestuvanje(host_id);
    create index if not exists korisnik_index_on_smestuvanje on smestuvanje(korisnik);
  views.sql: |
    create or replace view public.smestuvanje_stats_by_user(korisnik, count) as
    SELECT smestuvanje.korisnik AS korisnik,
           count(*) AS count
    FROM smestuvanje
    GROUP BY smestuvanje.korisnik;

    alter table public.smestuvanje_stats_by_user
        owner to emt;


    create materialized view if not exists public.smestuvanje_stats_by_host as
    SELECT host_id,count(*) AS number_of_smestuvanje
    FROM smestuvanje
    GROUP BY host_id;

    create materialized view if not exists public.host_by_country as
    select country_id,count(*) as number_of_hosts
    from host
    group by country_id
