spring.application.name=lab_EMT

spring.jpa.show-sql=true

#spring.profiles.active=h2
spring.profiles.active=postgres

spring.thymeleaf.check-template-location=false
spring.jpa.open-in-view=true


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

